import { MedicationDosingType } from '@prisma/client';

/**
 * პედიატრიაში გამოყენებული პრეპარატები.
 *
 * დოზირება საერთაშორისო პედიატრიულ ცნობარებს ეყრდნობა და ბავშვის
 * წონაზე ან ასაკზე ითვლება. კალკულატორი დღიურ ზღვარს ვერასდროს
 * გასცდება — ეს თავად გამოთვლაშია ჩაშენებული.
 *
 * ეს სია ამოსავალი წერტილია და პედიატრის გადაწყვეტილებას არ ცვლის.
 * ექიმს დოზის შეცვლა ყოველთვის შეუძლია.
 */
export const MEDICATION_SEED = [
  {
    slug: 'paracetamol',
    name: 'პარაცეტამოლი',
    dosingType: MedicationDosingType.PER_KG,
    mgPerKgMin: 10,
    mgPerKgMax: 15,
    intervalHoursMin: 6,
    intervalHoursMax: 6,
    maxDailyMg: 2000,
    minAgeMonths: 0,
    minWeightKg: 3,
    sortOrder: 1,
    note: 'ცხელებასა და ტკივილზე. ყველაზე ხშირად გამოყენებული საშუალება ბავშვებში.',
    concentrations: [
      { label: 'სიროფი 120 მგ / 5 მლ', mg: 120, ml: 5 },
      { label: 'სიროფი 250 მგ / 5 მლ', mg: 250, ml: 5 },
      { label: 'წვეთები 100 მგ / 1 მლ', mg: 100, ml: 1 },
    ],
  },
  {
    slug: 'ibuprofen',
    name: 'იბუპროფენი',
    dosingType: MedicationDosingType.PER_KG,
    mgPerKgMin: 5,
    mgPerKgMax: 10,
    intervalHoursMin: 8,
    intervalHoursMax: 8,
    maxDailyMg: 1200,
    minAgeMonths: 3,
    minWeightKg: 5,
    sortOrder: 2,
    note: 'ცხელებასა და ანთებით ტკივილზე. ჩუტყვავილასა და დეჰიდრატაციისას არ გამოიყენება.',
    concentrations: [
      { label: 'სუსპენზია 100 მგ / 5 მლ', mg: 100, ml: 5 },
      { label: 'სუსპენზია 200 მგ / 5 მლ', mg: 200, ml: 5 },
    ],
  },
  {
    slug: 'amoxicillin',
    name: 'ამოქსიცილინი',
    dosingType: MedicationDosingType.PER_KG,
    mgPerKgMin: 12.5,
    mgPerKgMax: 22.5,
    intervalHoursMin: 12,
    intervalHoursMax: 12,
    maxDailyMg: 3000,
    minAgeMonths: 1,
    minWeightKg: 4,
    sortOrder: 3,
    note: 'ანტიბიოტიკი. მხოლოდ ექიმის დანიშნულებით; კურსი ბოლომდე.',
    concentrations: [
      { label: 'სუსპენზია 125 მგ / 5 მლ', mg: 125, ml: 5 },
      { label: 'სუსპენზია 250 მგ / 5 მლ', mg: 250, ml: 5 },
    ],
  },
  {
    slug: 'amoxicillin-clavulanate',
    name: 'ამოქსიცილინი კლავულანატით',
    dosingType: MedicationDosingType.PER_KG,
    mgPerKgMin: 11.25,
    mgPerKgMax: 22.5,
    intervalHoursMin: 12,
    intervalHoursMax: 12,
    maxDailyMg: 2800,
    minAgeMonths: 2,
    minWeightKg: 5,
    sortOrder: 4,
    note: 'ანტიბიოტიკი გაფართოებული სპექტრით. ხშირად იწვევს ფაღარათს — მიიღება საკვებთან ერთად.',
    concentrations: [
      { label: 'სუსპენზია 156 მგ / 5 მლ', mg: 156, ml: 5 },
      { label: 'სუსპენზია 312 მგ / 5 მლ', mg: 312, ml: 5 },
    ],
  },
  {
    slug: 'azithromycin',
    name: 'აზითრომიცინი',
    dosingType: MedicationDosingType.PER_KG,
    mgPerKgMin: 10,
    mgPerKgMax: 10,
    intervalHoursMin: 24,
    intervalHoursMax: 24,
    maxDailyMg: 500,
    minAgeMonths: 6,
    minWeightKg: 5,
    sortOrder: 5,
    note: 'დღეში ერთხელ, კურსი ჩვეულებრივ 3 დღე.',
    concentrations: [
      { label: 'სუსპენზია 100 მგ / 5 მლ', mg: 100, ml: 5 },
      { label: 'სუსპენზია 200 მგ / 5 მლ', mg: 200, ml: 5 },
    ],
  },
  {
    slug: 'cefuroxime',
    name: 'ცეფუროქსიმი',
    dosingType: MedicationDosingType.PER_KG,
    mgPerKgMin: 10,
    mgPerKgMax: 15,
    intervalHoursMin: 12,
    intervalHoursMax: 12,
    maxDailyMg: 1000,
    minAgeMonths: 3,
    minWeightKg: 5,
    sortOrder: 6,
    note: 'ანტიბიოტიკი. მიიღება საკვების შემდეგ.',
    concentrations: [
      { label: 'სუსპენზია 125 მგ / 5 მლ', mg: 125, ml: 5 },
      { label: 'სუსპენზია 250 მგ / 5 მლ', mg: 250, ml: 5 },
    ],
  },
  {
    slug: 'clarithromycin',
    name: 'კლარითრომიცინი',
    dosingType: MedicationDosingType.PER_KG,
    mgPerKgMin: 7.5,
    mgPerKgMax: 7.5,
    intervalHoursMin: 12,
    intervalHoursMax: 12,
    maxDailyMg: 1000,
    minAgeMonths: 6,
    minWeightKg: 8,
    sortOrder: 7,
    note: 'ალტერნატივა პენიცილინზე ალერგიისას.',
    concentrations: [
      { label: 'სუსპენზია 125 მგ / 5 მლ', mg: 125, ml: 5 },
      { label: 'სუსპენზია 250 მგ / 5 მლ', mg: 250, ml: 5 },
    ],
  },
  {
    slug: 'cetirizine',
    name: 'ცეტირიზინი',
    dosingType: MedicationDosingType.BY_AGE,
    ageBands: [
      { label: '6–12 თვე', untilMonths: 12, mg: 2.5 },
      { label: '1–5 წელი', untilMonths: 72, mg: 5 },
      { label: '6 წლიდან', untilMonths: 217, mg: 10 },
    ],
    intervalHoursMin: 24,
    intervalHoursMax: 24,
    maxDailyMg: 10,
    minAgeMonths: 6,
    minWeightKg: 5,
    sortOrder: 8,
    note: 'ანტიჰისტამინი. დღეში ერთხელ, საღამოს.',
    concentrations: [
      { label: 'წვეთები 10 მგ / 1 მლ', mg: 10, ml: 1 },
      { label: 'სიროფი 5 მგ / 5 მლ', mg: 5, ml: 5 },
    ],
  },
  {
    slug: 'loratadine',
    name: 'ლორატადინი',
    dosingType: MedicationDosingType.BY_AGE,
    ageBands: [
      { label: '2–6 წელი', untilMonths: 72, mg: 5 },
      { label: '6 წლიდან', untilMonths: 217, mg: 10 },
    ],
    intervalHoursMin: 24,
    intervalHoursMax: 24,
    maxDailyMg: 10,
    minAgeMonths: 24,
    minWeightKg: 10,
    sortOrder: 9,
    note: 'ანტიჰისტამინი. ძილიანობას ნაკლებად იწვევს.',
    concentrations: [
      { label: 'სიროფი 5 მგ / 5 მლ', mg: 5, ml: 5 },
    ],
  },
  {
    slug: 'fenistil',
    name: 'ფენისტილი',
    dosingType: MedicationDosingType.BY_AGE,
    ageBands: [
      { label: '1–12 თვე', untilMonths: 12, mg: 3 },
      { label: '1–3 წელი', untilMonths: 36, mg: 10 },
      { label: '3 წლიდან', untilMonths: 217, mg: 15 },
    ],
    intervalHoursMin: 8,
    intervalHoursMax: 8,
    maxDailyMg: 60,
    minAgeMonths: 1,
    minWeightKg: 4,
    sortOrder: 10,
    note: 'დოზა წვეთებშია. ქავილსა და ალერგიულ გამონაყარზე.',
    concentrations: [
      { label: 'წვეთები', mg: 1, ml: 1 },
    ],
  },
  {
    slug: 'dexamethasone',
    name: 'დექსამეტაზონი',
    dosingType: MedicationDosingType.PER_KG,
    mgPerKgMin: 0.15,
    mgPerKgMax: 0.6,
    intervalHoursMin: 24,
    intervalHoursMax: 24,
    maxDailyMg: 16,
    minAgeMonths: 0,
    minWeightKg: 3,
    sortOrder: 11,
    note: 'მხოლოდ ექიმის დანიშნულებით — ცრუ კრუპსა და მძიმე ანთებაზე.',
    concentrations: [
      { label: 'ხსნარი 4 მგ / 1 მლ', mg: 4, ml: 1 },
    ],
  },
  {
    slug: 'prednisolone',
    name: 'პრედნიზოლონი',
    dosingType: MedicationDosingType.PER_KG,
    mgPerKgMin: 1,
    mgPerKgMax: 2,
    intervalHoursMin: 24,
    intervalHoursMax: 24,
    maxDailyMg: 40,
    minAgeMonths: 1,
    minWeightKg: 4,
    sortOrder: 12,
    note: 'მოკლე კურსი ექიმის დანიშნულებით — ასთმის გამწვავებაზე.',
    concentrations: [
      { label: 'სიროფი 15 მგ / 5 მლ', mg: 15, ml: 5 },
    ],
  },
  {
    slug: 'salbutamol',
    name: 'სალბუტამოლი',
    dosingType: MedicationDosingType.BY_AGE,
    ageBands: [
      { label: 'ყველა ასაკი', untilMonths: 217, mg: 100 },
    ],
    intervalHoursMin: 6,
    intervalHoursMax: 6,
    maxDailyMg: 800,
    minAgeMonths: 0,
    minWeightKg: 3,
    sortOrder: 13,
    note: 'დოზა მიკროგრამებშია. ინჰალაციით, სპეისერით. ხიხინსა და სუნთქვის გაძნელებაზე.',
    concentrations: [
      { label: 'ინჰალატორი 100 მკგ / დოზა', mg: 100, ml: 1 },
    ],
  },
  {
    slug: 'ors',
    name: 'რეჰიდრატაციის ხსნარი',
    dosingType: MedicationDosingType.PER_KG,
    mgPerKgMin: 50,
    mgPerKgMax: 100,
    intervalHoursMin: 4,
    intervalHoursMax: 4,
    maxDailyMg: 200000,
    minAgeMonths: 0,
    minWeightKg: 2,
    sortOrder: 14,
    note: 'დოზა მილილიტრებშია — მცირე ულუფებით, ხშირად, ყოველი განავლის შემდეგ.',
    concentrations: [
      { label: 'მზა ხსნარი', mg: 1, ml: 1 },
    ],
  },
  {
    slug: 'saline-nasal',
    name: 'ფიზიოლოგიური ხსნარი — ცხვირისთვის',
    dosingType: MedicationDosingType.BY_AGE,
    ageBands: [
      { label: '0–12 თვე', untilMonths: 12, mg: 2 },
      { label: '1 წლიდან', untilMonths: 217, mg: 3 },
    ],
    intervalHoursMin: 6,
    intervalHoursMax: 6,
    maxDailyMg: 100,
    minAgeMonths: 0,
    minWeightKg: 0,
    sortOrder: 15,
    note: 'დოზა წვეთებშია. კვებამდე გამორეცხვა ამარტივებს წოვას.',
    concentrations: [
      { label: 'წვეთები', mg: 1, ml: 1 },
    ],
  },
  {
    slug: 'vitamin-d',
    name: 'D ვიტამინი',
    dosingType: MedicationDosingType.BY_AGE,
    ageBands: [
      { label: '0–12 თვე', untilMonths: 12, mg: 400 },
      { label: '1 წლიდან', untilMonths: 217, mg: 600 },
    ],
    intervalHoursMin: 24,
    intervalHoursMax: 24,
    maxDailyMg: 1000,
    minAgeMonths: 0,
    minWeightKg: 2,
    sortOrder: 16,
    note: 'დოზა საერთაშორისო ერთეულებშია. პროფილაქტიკურად, დღეში ერთხელ.',
    concentrations: [
      { label: 'წვეთები 400 სე / 1 წვეთი', mg: 400, ml: 1 },
    ],
  },
  {
    slug: 'iron',
    name: 'რკინის პრეპარატი',
    dosingType: MedicationDosingType.PER_KG,
    mgPerKgMin: 3,
    mgPerKgMax: 6,
    intervalHoursMin: 24,
    intervalHoursMax: 24,
    maxDailyMg: 200,
    minAgeMonths: 4,
    minWeightKg: 5,
    sortOrder: 17,
    note: 'კვებამდე, C ვიტამინთან ერთად. განავალს ამუქებს — ეს ნორმაა.',
    concentrations: [
      { label: 'სიროფი 50 მგ / 5 მლ', mg: 50, ml: 5 },
    ],
  },
  {
    slug: 'zinc',
    name: 'თუთია',
    dosingType: MedicationDosingType.BY_AGE,
    ageBands: [
      { label: '0–6 თვე', untilMonths: 6, mg: 10 },
      { label: '6 თვიდან', untilMonths: 217, mg: 20 },
    ],
    intervalHoursMin: 24,
    intervalHoursMax: 24,
    maxDailyMg: 20,
    minAgeMonths: 0,
    minWeightKg: 3,
    sortOrder: 18,
    note: 'ფაღარათის ხანგრძლივობას ამცირებს — კურსი 10–14 დღე.',
    concentrations: [
      { label: 'სიროფი 20 მგ / 5 მლ', mg: 20, ml: 5 },
    ],
  },
  {
    slug: 'smectite',
    name: 'დიოსმექტიტი',
    dosingType: MedicationDosingType.BY_AGE,
    ageBands: [
      { label: '0–12 თვე', untilMonths: 12, mg: 1 },
      { label: '1–2 წელი', untilMonths: 24, mg: 2 },
      { label: '2 წლიდან', untilMonths: 217, mg: 3 },
    ],
    intervalHoursMin: 8,
    intervalHoursMax: 8,
    maxDailyMg: 9,
    minAgeMonths: 0,
    minWeightKg: 3,
    sortOrder: 19,
    note: 'დოზა პაკეტებშია დღეში. სხვა წამლისგან ცალკე, 2 საათის ინტერვალით.',
    concentrations: [
      { label: 'პაკეტი 3 გ', mg: 1, ml: 1 },
    ],
  },
  {
    slug: 'simethicone',
    name: 'სიმეთიკონი',
    dosingType: MedicationDosingType.BY_AGE,
    ageBands: [
      { label: '0–12 თვე', untilMonths: 12, mg: 20 },
      { label: '1 წლიდან', untilMonths: 217, mg: 40 },
    ],
    intervalHoursMin: 6,
    intervalHoursMax: 6,
    maxDailyMg: 240,
    minAgeMonths: 0,
    minWeightKg: 2,
    sortOrder: 20,
    note: 'შებერილობასა და კოლიკაზე, კვების შემდეგ.',
    concentrations: [
      { label: 'ემულსია 40 მგ / 1 მლ', mg: 40, ml: 1 },
    ],
  },
  {
    slug: 'lactulose',
    name: 'ლაქტულოზა',
    dosingType: MedicationDosingType.PER_KG,
    mgPerKgMin: 500,
    mgPerKgMax: 1000,
    intervalHoursMin: 24,
    intervalHoursMax: 24,
    maxDailyMg: 30000,
    minAgeMonths: 1,
    minWeightKg: 4,
    sortOrder: 21,
    note: 'ყაბზობაზე. ეფექტი 1–2 დღეში ჩნდება; დოზა ინდივიდუალურად ირჩევა.',
    concentrations: [
      { label: 'სიროფი 667 მგ / 1 მლ', mg: 667, ml: 1 },
    ],
  },
  {
    slug: 'nystatin',
    name: 'ნისტატინი',
    dosingType: MedicationDosingType.BY_AGE,
    ageBands: [
      { label: 'ყველა ასაკი', untilMonths: 217, mg: 100000 },
    ],
    intervalHoursMin: 6,
    intervalHoursMax: 6,
    maxDailyMg: 800000,
    minAgeMonths: 0,
    minWeightKg: 2,
    sortOrder: 22,
    note: 'დოზა საერთაშორისო ერთეულებშია. პირის ღრუს კანდიდოზზე, კვების შემდეგ.',
    concentrations: [
      { label: 'სუსპენზია 100000 სე / 1 მლ', mg: 100000, ml: 1 },
    ],
  },
  {
    slug: 'mebendazole',
    name: 'მებენდაზოლი',
    dosingType: MedicationDosingType.BY_AGE,
    ageBands: [
      { label: '1 წლიდან', untilMonths: 217, mg: 100 },
    ],
    intervalHoursMin: 24,
    intervalHoursMax: 24,
    maxDailyMg: 200,
    minAgeMonths: 12,
    minWeightKg: 10,
    sortOrder: 23,
    note: 'პარაზიტების საწინააღმდეგო. მკურნალობა ოჯახის ყველა წევრს ერთდროულად.',
    concentrations: [
      { label: 'სუსპენზია 100 მგ / 5 მლ', mg: 100, ml: 5 },
    ],
  },
  {
    slug: 'ondansetron',
    name: 'ონდანსეტრონი',
    dosingType: MedicationDosingType.PER_KG,
    mgPerKgMin: 0.1,
    mgPerKgMax: 0.15,
    intervalHoursMin: 8,
    intervalHoursMax: 8,
    maxDailyMg: 12,
    minAgeMonths: 6,
    minWeightKg: 8,
    sortOrder: 24,
    note: 'ღებინების საწინააღმდეგო. ექიმის დანიშნულებით, გასტროენტერიტისას რეჰიდრატაციის გასაადვილებლად.',
    concentrations: [
      { label: 'სიროფი 4 მგ / 5 მლ', mg: 4, ml: 5 },
    ],
  },
  {
    slug: 'montelukast',
    name: 'მონტელუკასტი',
    dosingType: MedicationDosingType.BY_AGE,
    ageBands: [
      { label: '6 თვიდან 5 წლამდე', untilMonths: 72, mg: 4 },
      { label: '6–14 წელი', untilMonths: 180, mg: 5 },
      { label: '15 წლიდან', untilMonths: 217, mg: 10 },
    ],
    intervalHoursMin: 24,
    intervalHoursMax: 24,
    maxDailyMg: 10,
    minAgeMonths: 6,
    minWeightKg: 6,
    sortOrder: 25,
    note: 'ასთმისა და ალერგიული რინიტის ხანგრძლივი კონტროლი. საღამოს, დღეში ერთხელ.',
    concentrations: [
      { label: 'საღეჭი ტაბლეტი 4 მგ', mg: 4, ml: 1 },
      { label: 'საღეჭი ტაბლეტი 5 მგ', mg: 5, ml: 1 },
    ],
  },
  {
    slug: 'budesonide-inhaled',
    name: 'ბუდეზონიდი — ინჰალაციური',
    dosingType: MedicationDosingType.BY_AGE,
    ageBands: [
      { label: '12 წლამდე', untilMonths: 144, mg: 200 },
      { label: '12 წლიდან', untilMonths: 217, mg: 400 },
    ],
    intervalHoursMin: 12,
    intervalHoursMax: 12,
    maxDailyMg: 800,
    minAgeMonths: 6,
    minWeightKg: 6,
    sortOrder: 26,
    note: 'დოზა მიკროგრამებშია. ასთმის ბაზისური მკურნალობა — ინჰალაციის შემდეგ პირის გამორეცხვა.',
    concentrations: [
      { label: 'ინჰალატორი 200 მკგ / დოზა', mg: 200, ml: 1 },
    ],
  },
  {
    slug: 'fluticasone-nasal',
    name: 'ფლუტიკაზონი — ცხვირის სპრეი',
    dosingType: MedicationDosingType.BY_AGE,
    ageBands: [
      { label: '4–11 წელი', untilMonths: 144, mg: 50 },
      { label: '12 წლიდან', untilMonths: 217, mg: 100 },
    ],
    intervalHoursMin: 24,
    intervalHoursMax: 24,
    maxDailyMg: 200,
    minAgeMonths: 48,
    minWeightKg: 15,
    sortOrder: 27,
    note: 'დოზა მიკროგრამებშია თითო ნესტოზე. ალერგიულ რინიტზე, დღეში ერთხელ.',
    concentrations: [
      { label: 'სპრეი 50 მკგ / დოზა', mg: 50, ml: 1 },
    ],
  },
  {
    slug: 'cefixime',
    name: 'ცეფიქსიმი',
    dosingType: MedicationDosingType.PER_KG,
    mgPerKgMin: 4,
    mgPerKgMax: 4,
    intervalHoursMin: 12,
    intervalHoursMax: 12,
    maxDailyMg: 400,
    minAgeMonths: 6,
    minWeightKg: 6,
    sortOrder: 28,
    note: 'ანტიბიოტიკი — ხშირად საშარდე გზების ინფექციაზე. ექიმის დანიშნულებით.',
    concentrations: [
      { label: 'სუსპენზია 100 მგ / 5 მლ', mg: 100, ml: 5 },
    ],
  },
  {
    slug: 'metronidazole',
    name: 'მეტრონიდაზოლი',
    dosingType: MedicationDosingType.PER_KG,
    mgPerKgMin: 5,
    mgPerKgMax: 7.5,
    intervalHoursMin: 8,
    intervalHoursMax: 8,
    maxDailyMg: 1200,
    minAgeMonths: 1,
    minWeightKg: 4,
    sortOrder: 29,
    note: 'ლამბლიოზსა და ანაერობულ ინფექციებზე. ალკოჰოლის შემცველ სიროფებთან არ ერწყმის.',
    concentrations: [
      { label: 'სუსპენზია 125 მგ / 5 მლ', mg: 125, ml: 5 },
    ],
  },
  {
    slug: 'fluconazole',
    name: 'ფლუკონაზოლი',
    dosingType: MedicationDosingType.PER_KG,
    mgPerKgMin: 3,
    mgPerKgMax: 6,
    intervalHoursMin: 24,
    intervalHoursMax: 24,
    maxDailyMg: 400,
    minAgeMonths: 1,
    minWeightKg: 4,
    sortOrder: 30,
    note: 'სოკოვანი ინფექციები. ექიმის დანიშნულებით.',
    concentrations: [
      { label: 'სუსპენზია 50 მგ / 5 მლ', mg: 50, ml: 5 },
    ],
  },
  {
    slug: 'permethrin',
    name: 'პერმეთრინი',
    dosingType: MedicationDosingType.BY_AGE,
    ageBands: [
      { label: 'ყველა ასაკი', untilMonths: 217, mg: 1 },
    ],
    intervalHoursMin: 24,
    intervalHoursMax: 24,
    maxDailyMg: 2,
    minAgeMonths: 2,
    minWeightKg: 4,
    sortOrder: 31,
    note: 'გარეგანი გამოყენება მუნსა და ტილზე. დოზა წასმის რაოდენობაა — მკურნალობა ოჯახის ყველა წევრს ერთდროულად.',
    concentrations: [
      { label: 'კრემი 5%', mg: 1, ml: 1 },
    ],
  },
  {
    slug: 'albendazole',
    name: 'ალბენდაზოლი',
    dosingType: MedicationDosingType.BY_AGE,
    ageBands: [
      { label: '1–2 წელი', untilMonths: 24, mg: 200 },
      { label: '2 წლიდან', untilMonths: 217, mg: 400 },
    ],
    intervalHoursMin: 24,
    intervalHoursMax: 24,
    maxDailyMg: 400,
    minAgeMonths: 12,
    minWeightKg: 10,
    sortOrder: 32,
    note: 'პარაზიტების საწინააღმდეგო. ერთჯერადად, გამეორება 2 კვირაში.',
    concentrations: [
      { label: 'სუსპენზია 400 მგ / 10 მლ', mg: 400, ml: 10 },
    ],
  },
  {
    slug: 'hydrocortisone-topical',
    name: 'ჰიდროკორტიზონი — მალამო',
    dosingType: MedicationDosingType.BY_AGE,
    ageBands: [
      { label: 'ყველა ასაკი', untilMonths: 217, mg: 1 },
    ],
    intervalHoursMin: 12,
    intervalHoursMax: 12,
    maxDailyMg: 2,
    minAgeMonths: 3,
    minWeightKg: 5,
    sortOrder: 33,
    note: 'დოზა წასმის რაოდენობაა დღეში. ატოპიური დერმატიტის გამწვავებაზე, მოკლე კურსი; სახეზე ფრთხილად.',
    concentrations: [
      { label: 'მალამო 1%', mg: 1, ml: 1 },
    ],
  },
  {
    slug: 'mupirocin',
    name: 'მუპიროცინი — მალამო',
    dosingType: MedicationDosingType.BY_AGE,
    ageBands: [
      { label: 'ყველა ასაკი', untilMonths: 217, mg: 1 },
    ],
    intervalHoursMin: 8,
    intervalHoursMax: 8,
    maxDailyMg: 3,
    minAgeMonths: 2,
    minWeightKg: 4,
    sortOrder: 34,
    note: 'დოზა წასმის რაოდენობაა დღეში. იმპეტიგოსა და კანის ლოკალურ ბაქტერიულ ინფექციაზე.',
    concentrations: [
      { label: 'მალამო 2%', mg: 1, ml: 1 },
    ],
  },
  {
    slug: 'dexpanthenol',
    name: 'დექსპანთენოლი — კრემი',
    dosingType: MedicationDosingType.BY_AGE,
    ageBands: [
      { label: 'ყველა ასაკი', untilMonths: 217, mg: 1 },
    ],
    intervalHoursMin: 6,
    intervalHoursMax: 6,
    maxDailyMg: 5,
    minAgeMonths: 0,
    minWeightKg: 2,
    sortOrder: 35,
    note: 'დოზა წასმის რაოდენობაა დღეში. პელენების დერმატიტსა და კანის გაღიზიანებაზე.',
    concentrations: [
      { label: 'კრემი 5%', mg: 1, ml: 1 },
    ],
  },
  {
    slug: 'probiotic',
    name: 'პრობიოტიკი',
    dosingType: MedicationDosingType.BY_AGE,
    ageBands: [
      { label: '0–12 თვე', untilMonths: 12, mg: 1 },
      { label: '1 წლიდან', untilMonths: 217, mg: 2 },
    ],
    intervalHoursMin: 12,
    intervalHoursMax: 24,
    maxDailyMg: 4,
    minAgeMonths: 0,
    minWeightKg: 2,
    sortOrder: 36,
    note: 'დოზა პაკეტებშია დღეში. ანტიბიოტიკთან ერთად მიღებისას 2 საათის ინტერვალით.',
    concentrations: [{ label: 'პაკეტი', mg: 1, ml: 1 }],
  },
  {
    slug: 'ambroxol',
    name: 'ამბროქსოლი',
    dosingType: MedicationDosingType.BY_AGE,
    ageBands: [
      { label: '0–2 წელი', untilMonths: 24, mg: 7.5 },
      { label: '2–6 წელი', untilMonths: 72, mg: 15 },
      { label: '6–12 წელი', untilMonths: 144, mg: 30 },
      { label: '12 წლიდან', untilMonths: 217, mg: 30 },
    ],
    intervalHoursMin: 8,
    intervalHoursMax: 12,
    maxDailyMg: 90,
    minAgeMonths: 0,
    minWeightKg: 3,
    sortOrder: 37,
    note: 'ლორწოს გამათხელებელი. სითხის უხვი მიღება აძლიერებს ეფექტს.',
    concentrations: [{ label: 'სიროფი 15 მგ / 5 მლ', mg: 15, ml: 5 }],
  },
  {
    slug: 'acetylcysteine',
    name: 'აცეტილცისტეინი',
    dosingType: MedicationDosingType.BY_AGE,
    ageBands: [
      { label: '2–6 წელი', untilMonths: 72, mg: 100 },
      { label: '6 წლიდან', untilMonths: 217, mg: 200 },
    ],
    intervalHoursMin: 8,
    intervalHoursMax: 12,
    maxDailyMg: 600,
    minAgeMonths: 24,
    minWeightKg: 10,
    sortOrder: 38,
    note: 'ლორწოს გამათხელებელი. საღამოს გვიან მიღება არ არის სასურველი.',
    concentrations: [{ label: 'პაკეტი 100 მგ', mg: 100, ml: 1 }],
  },
  {
    slug: 'oseltamivir',
    name: 'ოსელტამივირი',
    dosingType: MedicationDosingType.PER_KG,
    mgPerKgMin: 2,
    mgPerKgMax: 3,
    intervalHoursMin: 12,
    intervalHoursMax: 12,
    maxDailyMg: 150,
    minAgeMonths: 1,
    minWeightKg: 4,
    sortOrder: 39,
    note: 'გრიპის საწინააღმდეგო. ეფექტურია პირველი 48 საათის განმავლობაში.',
    concentrations: [{ label: 'სუსპენზია 30 მგ / 5 მლ', mg: 30, ml: 5 }],
  },
  {
    slug: 'acyclovir',
    name: 'აციკლოვირი',
    dosingType: MedicationDosingType.PER_KG,
    mgPerKgMin: 20,
    mgPerKgMax: 20,
    intervalHoursMin: 6,
    intervalHoursMax: 6,
    maxDailyMg: 3200,
    minAgeMonths: 1,
    minWeightKg: 4,
    sortOrder: 40,
    note: 'ჰერპესულ ინფექციებზე. ეფექტი პირველი 72 საათის დაწყებაზეა დამოკიდებული.',
    concentrations: [{ label: 'სუსპენზია 200 მგ / 5 მლ', mg: 200, ml: 5 }],
  },
  {
    slug: 'nitrofurantoin',
    name: 'ნიტროფურანტოინი',
    dosingType: MedicationDosingType.PER_KG,
    mgPerKgMin: 1.25,
    mgPerKgMax: 1.75,
    intervalHoursMin: 6,
    intervalHoursMax: 6,
    maxDailyMg: 400,
    minAgeMonths: 3,
    minWeightKg: 5,
    sortOrder: 41,
    note: 'საშარდე გზების ინფექციაზე. მიიღება საკვებთან ერთად.',
    concentrations: [{ label: 'სუსპენზია 25 მგ / 5 მლ', mg: 25, ml: 5 }],
  },
  {
    slug: 'cotrimoxazole',
    name: 'კო-ტრიმოქსაზოლი',
    dosingType: MedicationDosingType.PER_KG,
    mgPerKgMin: 4,
    mgPerKgMax: 6,
    intervalHoursMin: 12,
    intervalHoursMax: 12,
    maxDailyMg: 320,
    minAgeMonths: 2,
    minWeightKg: 4,
    sortOrder: 42,
    note: 'დოზა ტრიმეთოპრიმზეა. უხვი სითხე მიღების პერიოდში.',
    concentrations: [{ label: 'სუსპენზია 40 მგ / 5 მლ', mg: 40, ml: 5 }],
  },
  {
    slug: 'ceftriaxone',
    name: 'ცეფტრიაქსონი',
    dosingType: MedicationDosingType.PER_KG,
    mgPerKgMin: 50,
    mgPerKgMax: 75,
    intervalHoursMin: 24,
    intervalHoursMax: 24,
    maxDailyMg: 2000,
    minAgeMonths: 0,
    minWeightKg: 2,
    sortOrder: 43,
    note: 'საინექციო ანტიბიოტიკი — სტაციონარული ან დღის სტაციონარის პირობებში.',
    concentrations: [{ label: 'ფლაკონი 500 მგ', mg: 500, ml: 5 }],
  },
  {
    slug: 'tobramycin-eye',
    name: 'ტობრამიცინი — თვალის წვეთები',
    dosingType: MedicationDosingType.BY_AGE,
    ageBands: [{ label: 'ყველა ასაკი', untilMonths: 217, mg: 1 }],
    intervalHoursMin: 4,
    intervalHoursMax: 6,
    maxDailyMg: 6,
    minAgeMonths: 1,
    minWeightKg: 3,
    sortOrder: 44,
    note: 'დოზა წვეთებშია თითო თვალზე. ბაქტერიულ კონიუნქტივიტზე.',
    concentrations: [{ label: 'წვეთები 0.3%', mg: 1, ml: 1 }],
  },
  {
    slug: 'ear-drops-analgesic',
    name: 'ყურის ტკივილგამაყუჩებელი წვეთები',
    dosingType: MedicationDosingType.BY_AGE,
    ageBands: [
      { label: '0–12 თვე', untilMonths: 12, mg: 2 },
      { label: '1 წლიდან', untilMonths: 217, mg: 4 },
    ],
    intervalHoursMin: 8,
    intervalHoursMax: 12,
    maxDailyMg: 12,
    minAgeMonths: 1,
    minWeightKg: 3,
    sortOrder: 45,
    note: 'დოზა წვეთებშია. ყურის აპკის პერფორაციისას დაუშვებელია — ჯერ ექიმმა უნდა დაათვალიეროს.',
    concentrations: [{ label: 'წვეთები', mg: 1, ml: 1 }],
  },
  {
    slug: 'xylometazoline',
    name: 'ქსილომეტაზოლინი — ცხვირის წვეთები',
    dosingType: MedicationDosingType.BY_AGE,
    ageBands: [
      { label: '2–6 წელი', untilMonths: 72, mg: 1 },
      { label: '6 წლიდან', untilMonths: 217, mg: 2 },
    ],
    intervalHoursMin: 8,
    intervalHoursMax: 12,
    maxDailyMg: 6,
    minAgeMonths: 24,
    minWeightKg: 10,
    sortOrder: 46,
    note: 'დოზა წვეთებშია თითო ნესტოზე. კურსი 5 დღეს არ უნდა აღემატებოდეს.',
    concentrations: [{ label: 'წვეთები 0.05%', mg: 1, ml: 1 }],
  },
  {
    slug: 'calcium',
    name: 'კალციუმი',
    dosingType: MedicationDosingType.BY_AGE,
    ageBands: [
      { label: '0–12 თვე', untilMonths: 12, mg: 260 },
      { label: '1–3 წელი', untilMonths: 48, mg: 700 },
      { label: '4–8 წელი', untilMonths: 108, mg: 1000 },
      { label: '9 წლიდან', untilMonths: 217, mg: 1300 },
    ],
    intervalHoursMin: 12,
    intervalHoursMax: 24,
    maxDailyMg: 1300,
    minAgeMonths: 0,
    minWeightKg: 3,
    sortOrder: 47,
    note: 'დღიური საჭიროება. რკინის პრეპარატთან ერთად არ მიიღება — 2 საათის ინტერვალით.',
    concentrations: [{ label: 'სიროფი 250 მგ / 5 მლ', mg: 250, ml: 5 }],
  },
  {
    slug: 'paracetamol-supp',
    name: 'პარაცეტამოლი — სანთელი',
    dosingType: MedicationDosingType.PER_KG,
    mgPerKgMin: 15,
    mgPerKgMax: 20,
    intervalHoursMin: 6,
    intervalHoursMax: 8,
    maxDailyMg: 2000,
    minAgeMonths: 0,
    minWeightKg: 4,
    sortOrder: 48,
    note: 'ღებინებისას, როცა პირით მიღება ვერ ხერხდება.',
    concentrations: [
      { label: 'სანთელი 125 მგ', mg: 125, ml: 1 },
      { label: 'სანთელი 250 მგ', mg: 250, ml: 1 },
    ],
  },
  {
    slug: 'ibuprofen-supp',
    name: 'იბუპროფენი — სანთელი',
    dosingType: MedicationDosingType.PER_KG,
    mgPerKgMin: 5,
    mgPerKgMax: 10,
    intervalHoursMin: 8,
    intervalHoursMax: 8,
    maxDailyMg: 1200,
    minAgeMonths: 3,
    minWeightKg: 6,
    sortOrder: 49,
    note: 'ღებინებისას ალტერნატივა. ჩუტყვავილასა და დეჰიდრატაციისას არ გამოიყენება.',
    concentrations: [{ label: 'სანთელი 60 მგ', mg: 60, ml: 1 }],
  },
  {
    slug: 'clotrimazole-topical',
    name: 'კლოტრიმაზოლი — კრემი',
    dosingType: MedicationDosingType.BY_AGE,
    ageBands: [{ label: 'ყველა ასაკი', untilMonths: 217, mg: 1 }],
    intervalHoursMin: 8,
    intervalHoursMax: 12,
    maxDailyMg: 3,
    minAgeMonths: 0,
    minWeightKg: 2,
    sortOrder: 50,
    note: 'დოზა წასმის რაოდენობაა დღეში. კანისა და პელენების სოკოვან ინფექციაზე.',
    concentrations: [{ label: 'კრემი 1%', mg: 1, ml: 1 }],
  },
  {
    slug: 'zinc-oxide',
    name: 'თუთიის ოქსიდი — პასტა',
    dosingType: MedicationDosingType.BY_AGE,
    ageBands: [{ label: 'ყველა ასაკი', untilMonths: 217, mg: 1 }],
    intervalHoursMin: 4,
    intervalHoursMax: 6,
    maxDailyMg: 6,
    minAgeMonths: 0,
    minWeightKg: 2,
    sortOrder: 51,
    note: 'დოზა წასმის რაოდენობაა დღეში. პელენების დერმატიტის დამცავი ფენა ყოველი გამოცვლისას.',
    concentrations: [{ label: 'პასტა', mg: 1, ml: 1 }],
  },
  {
    slug: 'teething-gel',
    name: 'ღრძილების გელი',
    dosingType: MedicationDosingType.BY_AGE,
    ageBands: [{ label: '3 თვიდან', untilMonths: 217, mg: 1 }],
    intervalHoursMin: 6,
    intervalHoursMax: 8,
    maxDailyMg: 4,
    minAgeMonths: 3,
    minWeightKg: 5,
    sortOrder: 52,
    note: 'დოზა წასმის რაოდენობაა დღეში. კბილების ამოსვლისას, კვებამდე.',
    concentrations: [{ label: 'გელი', mg: 1, ml: 1 }],
  },
  {
    slug: 'chlorhexidine',
    name: 'ქლორჰექსიდინი — ხსნარი',
    dosingType: MedicationDosingType.BY_AGE,
    ageBands: [{ label: '6 წლიდან', untilMonths: 217, mg: 10 }],
    intervalHoursMin: 8,
    intervalHoursMax: 12,
    maxDailyMg: 30,
    minAgeMonths: 72,
    minWeightKg: 18,
    sortOrder: 53,
    note: 'დოზა მილილიტრებშია გამოსავლებად. ყლაპვა დაუშვებელია — მხოლოდ იმ ასაკში, როცა ბავშვს ამის გაკეთება შეუძლია.',
    concentrations: [{ label: 'ხსნარი 0.05%', mg: 1, ml: 1 }],
  },
  {
    slug: 'folic-acid',
    name: 'ფოლიუმის მჟავა',
    dosingType: MedicationDosingType.BY_AGE,
    ageBands: [
      { label: '0–12 თვე', untilMonths: 12, mg: 0.065 },
      { label: '1–3 წელი', untilMonths: 48, mg: 0.15 },
      { label: '4 წლიდან', untilMonths: 217, mg: 0.2 },
    ],
    intervalHoursMin: 24,
    intervalHoursMax: 24,
    maxDailyMg: 1,
    minAgeMonths: 0,
    minWeightKg: 2,
    sortOrder: 54,
    note: 'ანემიის მკურნალობისას რკინასთან ერთად.',
    concentrations: [{ label: 'ტაბლეტი 1 მგ', mg: 1, ml: 1 }],
  },
  {
    slug: 'domperidone',
    name: 'დომპერიდონი',
    dosingType: MedicationDosingType.PER_KG,
    mgPerKgMin: 0.25,
    mgPerKgMax: 0.25,
    intervalHoursMin: 8,
    intervalHoursMax: 8,
    maxDailyMg: 30,
    minAgeMonths: 12,
    minWeightKg: 10,
    sortOrder: 55,
    note: 'გულისრევაზე. მოკლე კურსი და მხოლოდ ექიმის დანიშნულებით — გულის რითმზე ზემოქმედების გამო.',
    concentrations: [{ label: 'სუსპენზია 5 მგ / 5 მლ', mg: 5, ml: 5 }],
  },
];
