import { MedicationDosingType } from '@prisma/client';

/**
 * პედიატრიაში გამოყენებული პრეპარატები.
 *
 * დოზირება საერთაშორისო პედიატრიულ ცნობარებს ეყრდნობა და ბავშვის
 * წონაზე ან ასაკზე ითვლება. კალკულატორი დღიურ ზღვარს ვერასდროს
 * გასცდება — ეს თავად გამოთვლაშია ჩაშენებული.
 *
 * ეს სია ამოსავალი წერტილია და პედიატრის გადაწყვეტილებას არ ცვლის.
 * ექიმს დოზის შეცვლა ყოველთვის შეუძლია.
 */
export const MEDICATION_SEED = [
  {
    slug: 'paracetamol',
    name: 'პარაცეტამოლი',
    dosingType: MedicationDosingType.PER_KG,
    mgPerKgMin: 10,
    mgPerKgMax: 15,
    intervalHoursMin: 6,
    intervalHoursMax: 6,
    maxDailyMg: 2000,
    minAgeMonths: 0,
    minWeightKg: 3,
    sortOrder: 1,
    note: 'ცხელებასა და ტკივილზე. ყველაზე ხშირად გამოყენებული საშუალება ბავშვებში.',
    concentrations: [
      { label: 'სიროფი 120 მგ / 5 მლ', mg: 120, ml: 5 },
      { label: 'სიროფი 250 მგ / 5 მლ', mg: 250, ml: 5 },
      { label: 'წვეთები 100 მგ / 1 მლ', mg: 100, ml: 1 },
    ],
  },
  {
    slug: 'ibuprofen',
    name: 'იბუპროფენი',
    dosingType: MedicationDosingType.PER_KG,
    mgPerKgMin: 5,
    mgPerKgMax: 10,
    intervalHoursMin: 8,
    intervalHoursMax: 8,
    maxDailyMg: 1200,
    minAgeMonths: 3,
    minWeightKg: 5,
    sortOrder: 2,
    note: 'ცხელებასა და ანთებით ტკივილზე. ჩუტყვავილასა და დეჰიდრატაციისას არ გამოიყენება.',
    concentrations: [
      { label: 'სუსპენზია 100 მგ / 5 მლ', mg: 100, ml: 5 },
      { label: 'სუსპენზია 200 მგ / 5 მლ', mg: 200, ml: 5 },
    ],
  },
  {
    slug: 'amoxicillin',
    name: 'ამოქსიცილინი',
    dosingType: MedicationDosingType.PER_KG,
    mgPerKgMin: 12.5,
    mgPerKgMax: 22.5,
    intervalHoursMin: 12,
    intervalHoursMax: 12,
    maxDailyMg: 3000,
    minAgeMonths: 1,
    minWeightKg: 4,
    sortOrder: 3,
    note: 'ანტიბიოტიკი. მხოლოდ ექიმის დანიშნულებით; კურსი ბოლომდე.',
    concentrations: [
      { label: 'სუსპენზია 125 მგ / 5 მლ', mg: 125, ml: 5 },
      { label: 'სუსპენზია 250 მგ / 5 მლ', mg: 250, ml: 5 },
    ],
  },
  {
    slug: 'amoxicillin-clavulanate',
    name: 'ამოქსიცილინი კლავულანატით',
    dosingType: MedicationDosingType.PER_KG,
    mgPerKgMin: 11.25,
    mgPerKgMax: 22.5,
    intervalHoursMin: 12,
    intervalHoursMax: 12,
    maxDailyMg: 2800,
    minAgeMonths: 2,
    minWeightKg: 5,
    sortOrder: 4,
    note: 'ანტიბიოტიკი გაფართოებული სპექტრით. ხშირად იწვევს ფაღარათს — მიიღება საკვებთან ერთად.',
    concentrations: [
      { label: 'სუსპენზია 156 მგ / 5 მლ', mg: 156, ml: 5 },
      { label: 'სუსპენზია 312 მგ / 5 მლ', mg: 312, ml: 5 },
    ],
  },
  {
    slug: 'azithromycin',
    name: 'აზითრომიცინი',
    dosingType: MedicationDosingType.PER_KG,
    mgPerKgMin: 10,
    mgPerKgMax: 10,
    intervalHoursMin: 24,
    intervalHoursMax: 24,
    maxDailyMg: 500,
    minAgeMonths: 6,
    minWeightKg: 5,
    sortOrder: 5,
    note: 'დღეში ერთხელ, კურსი ჩვეულებრივ 3 დღე.',
    concentrations: [
      { label: 'სუსპენზია 100 მგ / 5 მლ', mg: 100, ml: 5 },
      { label: 'სუსპენზია 200 მგ / 5 მლ', mg: 200, ml: 5 },
    ],
  },
  {
    slug: 'cefuroxime',
    name: 'ცეფუროქსიმი',
    dosingType: MedicationDosingType.PER_KG,
    mgPerKgMin: 10,
    mgPerKgMax: 15,
    intervalHoursMin: 12,
    intervalHoursMax: 12,
    maxDailyMg: 1000,
    minAgeMonths: 3,
    minWeightKg: 5,
    sortOrder: 6,
    note: 'ანტიბიოტიკი. მიიღება საკვების შემდეგ.',
    concentrations: [
      { label: 'სუსპენზია 125 მგ / 5 მლ', mg: 125, ml: 5 },
      { label: 'სუსპენზია 250 მგ / 5 მლ', mg: 250, ml: 5 },
    ],
  },
  {
    slug: 'clarithromycin',
    name: 'კლარითრომიცინი',
    dosingType: MedicationDosingType.PER_KG,
    mgPerKgMin: 7.5,
    mgPerKgMax: 7.5,
    intervalHoursMin: 12,
    intervalHoursMax: 12,
    maxDailyMg: 1000,
    minAgeMonths: 6,
    minWeightKg: 8,
    sortOrder: 7,
    note: 'ალტერნატივა პენიცილინზე ალერგიისას.',
    concentrations: [
      { label: 'სუსპენზია 125 მგ / 5 მლ', mg: 125, ml: 5 },
      { label: 'სუსპენზია 250 მგ / 5 მლ', mg: 250, ml: 5 },
    ],
  },
  {
    slug: 'cetirizine',
    name: 'ცეტირიზინი',
    dosingType: MedicationDosingType.BY_AGE,
    ageBands: [
      { label: '6–12 თვე', untilMonths: 12, mg: 2.5 },
      { label: '1–5 წელი', untilMonths: 72, mg: 5 },
      { label: '6 წლიდან', untilMonths: 217, mg: 10 },
    ],
    intervalHoursMin: 24,
    intervalHoursMax: 24,
    maxDailyMg: 10,
    minAgeMonths: 6,
    minWeightKg: 5,
    sortOrder: 8,
    note: 'ანტიჰისტამინი. დღეში ერთხელ, საღამოს.',
    concentrations: [
      { label: 'წვეთები 10 მგ / 1 მლ', mg: 10, ml: 1 },
      { label: 'სიროფი 5 მგ / 5 მლ', mg: 5, ml: 5 },
    ],
  },
  {
    slug: 'loratadine',
    name: 'ლორატადინი',
    dosingType: MedicationDosingType.BY_AGE,
    ageBands: [
      { label: '2–6 წელი', untilMonths: 72, mg: 5 },
      { label: '6 წლიდან', untilMonths: 217, mg: 10 },
    ],
    intervalHoursMin: 24,
    intervalHoursMax: 24,
    maxDailyMg: 10,
    minAgeMonths: 24,
    minWeightKg: 10,
    sortOrder: 9,
    note: 'ანტიჰისტამინი. ძილიანობას ნაკლებად იწვევს.',
    concentrations: [
      { label: 'სიროფი 5 მგ / 5 მლ', mg: 5, ml: 5 },
    ],
  },
  {
    slug: 'fenistil',
    name: 'ფენისტილი',
    dosingType: MedicationDosingType.BY_AGE,
    ageBands: [
      { label: '1–12 თვე', untilMonths: 12, mg: 3 },
      { label: '1–3 წელი', untilMonths: 36, mg: 10 },
      { label: '3 წლიდან', untilMonths: 217, mg: 15 },
    ],
    intervalHoursMin: 8,
    intervalHoursMax: 8,
    maxDailyMg: 60,
    minAgeMonths: 1,
    minWeightKg: 4,
    sortOrder: 10,
    note: 'დოზა წვეთებშია. ქავილსა და ალერგიულ გამონაყარზე.',
    concentrations: [
      { label: 'წვეთები', mg: 1, ml: 1 },
    ],
  },
  {
    slug: 'dexamethasone',
    name: 'დექსამეტაზონი',
    dosingType: MedicationDosingType.PER_KG,
    mgPerKgMin: 0.15,
    mgPerKgMax: 0.6,
    intervalHoursMin: 24,
    intervalHoursMax: 24,
    maxDailyMg: 16,
    minAgeMonths: 0,
    minWeightKg: 3,
    sortOrder: 11,
    note: 'მხოლოდ ექიმის დანიშნულებით — ცრუ კრუპსა და მძიმე ანთებაზე.',
    concentrations: [
      { label: 'ხსნარი 4 მგ / 1 მლ', mg: 4, ml: 1 },
    ],
  },
  {
    slug: 'prednisolone',
    name: 'პრედნიზოლონი',
    dosingType: MedicationDosingType.PER_KG,
    mgPerKgMin: 1,
    mgPerKgMax: 2,
    intervalHoursMin: 24,
    intervalHoursMax: 24,
    maxDailyMg: 40,
    minAgeMonths: 1,
    minWeightKg: 4,
    sortOrder: 12,
    note: 'მოკლე კურსი ექიმის დანიშნულებით — ასთმის გამწვავებაზე.',
    concentrations: [
      { label: 'სიროფი 15 მგ / 5 მლ', mg: 15, ml: 5 },
    ],
  },
  {
    slug: 'salbutamol',
    name: 'სალბუტამოლი',
    dosingType: MedicationDosingType.BY_AGE,
    ageBands: [
      { label: 'ყველა ასაკი', untilMonths: 217, mg: 100 },
    ],
    intervalHoursMin: 6,
    intervalHoursMax: 6,
    maxDailyMg: 800,
    minAgeMonths: 0,
    minWeightKg: 3,
    sortOrder: 13,
    note: 'დოზა მიკროგრამებშია. ინჰალაციით, სპეისერით. ხიხინსა და სუნთქვის გაძნელებაზე.',
    concentrations: [
      { label: 'ინჰალატორი 100 მკგ / დოზა', mg: 100, ml: 1 },
    ],
  },
  {
    slug: 'ors',
    name: 'რეჰიდრატაციის ხსნარი',
    dosingType: MedicationDosingType.PER_KG,
    mgPerKgMin: 50,
    mgPerKgMax: 100,
    intervalHoursMin: 4,
    intervalHoursMax: 4,
    maxDailyMg: 200000,
    minAgeMonths: 0,
    minWeightKg: 2,
    sortOrder: 14,
    note: 'დოზა მილილიტრებშია — მცირე ულუფებით, ხშირად, ყოველი განავლის შემდეგ.',
    concentrations: [
      { label: 'მზა ხსნარი', mg: 1, ml: 1 },
    ],
  },
  {
    slug: 'saline-nasal',
    name: 'ფიზიოლოგიური ხსნარი — ცხვირისთვის',
    dosingType: MedicationDosingType.BY_AGE,
    ageBands: [
      { label: '0–12 თვე', untilMonths: 12, mg: 2 },
      { label: '1 წლიდან', untilMonths: 217, mg: 3 },
    ],
    intervalHoursMin: 6,
    intervalHoursMax: 6,
    maxDailyMg: 100,
    minAgeMonths: 0,
    minWeightKg: 0,
    sortOrder: 15,
    note: 'დოზა წვეთებშია. კვებამდე გამორეცხვა ამარტივებს წოვას.',
    concentrations: [
      { label: 'წვეთები', mg: 1, ml: 1 },
    ],
  },
  {
    slug: 'vitamin-d',
    name: 'D ვიტამინი',
    dosingType: MedicationDosingType.BY_AGE,
    ageBands: [
      { label: '0–12 თვე', untilMonths: 12, mg: 400 },
      { label: '1 წლიდან', untilMonths: 217, mg: 600 },
    ],
    intervalHoursMin: 24,
    intervalHoursMax: 24,
    maxDailyMg: 1000,
    minAgeMonths: 0,
    minWeightKg: 2,
    sortOrder: 16,
    note: 'დოზა საერთაშორისო ერთეულებშია. პროფილაქტიკურად, დღეში ერთხელ.',
    concentrations: [
      { label: 'წვეთები 400 სე / 1 წვეთი', mg: 400, ml: 1 },
    ],
  },
  {
    slug: 'iron',
    name: 'რკინის პრეპარატი',
    dosingType: MedicationDosingType.PER_KG,
    mgPerKgMin: 3,
    mgPerKgMax: 6,
    intervalHoursMin: 24,
    intervalHoursMax: 24,
    maxDailyMg: 200,
    minAgeMonths: 4,
    minWeightKg: 5,
    sortOrder: 17,
    note: 'კვებამდე, C ვიტამინთან ერთად. განავალს ამუქებს — ეს ნორმაა.',
    concentrations: [
      { label: 'სიროფი 50 მგ / 5 მლ', mg: 50, ml: 5 },
    ],
  },
  {
    slug: 'zinc',
    name: 'თუთია',
    dosingType: MedicationDosingType.BY_AGE,
    ageBands: [
      { label: '0–6 თვე', untilMonths: 6, mg: 10 },
      { label: '6 თვიდან', untilMonths: 217, mg: 20 },
    ],
    intervalHoursMin: 24,
    intervalHoursMax: 24,
    maxDailyMg: 20,
    minAgeMonths: 0,
    minWeightKg: 3,
    sortOrder: 18,
    note: 'ფაღარათის ხანგრძლივობას ამცირებს — კურსი 10–14 დღე.',
    concentrations: [
      { label: 'სიროფი 20 მგ / 5 მლ', mg: 20, ml: 5 },
    ],
  },
  {
    slug: 'smectite',
    name: 'დიოსმექტიტი',
    dosingType: MedicationDosingType.BY_AGE,
    ageBands: [
      { label: '0–12 თვე', untilMonths: 12, mg: 1 },
      { label: '1–2 წელი', untilMonths: 24, mg: 2 },
      { label: '2 წლიდან', untilMonths: 217, mg: 3 },
    ],
    intervalHoursMin: 8,
    intervalHoursMax: 8,
    maxDailyMg: 9,
    minAgeMonths: 0,
    minWeightKg: 3,
    sortOrder: 19,
    note: 'დოზა პაკეტებშია დღეში. სხვა წამლისგან ცალკე, 2 საათის ინტერვალით.',
    concentrations: [
      { label: 'პაკეტი 3 გ', mg: 1, ml: 1 },
    ],
  },
  {
    slug: 'simethicone',
    name: 'სიმეთიკონი',
    dosingType: MedicationDosingType.BY_AGE,
    ageBands: [
      { label: '0–12 თვე', untilMonths: 12, mg: 20 },
      { label: '1 წლიდან', untilMonths: 217, mg: 40 },
    ],
    intervalHoursMin: 6,
    intervalHoursMax: 6,
    maxDailyMg: 240,
    minAgeMonths: 0,
    minWeightKg: 2,
    sortOrder: 20,
    note: 'შებერილობასა და კოლიკაზე, კვების შემდეგ.',
    concentrations: [
      { label: 'ემულსია 40 მგ / 1 მლ', mg: 40, ml: 1 },
    ],
  },
  {
    slug: 'lactulose',
    name: 'ლაქტულოზა',
    dosingType: MedicationDosingType.PER_KG,
    mgPerKgMin: 500,
    mgPerKgMax: 1000,
    intervalHoursMin: 24,
    intervalHoursMax: 24,
    maxDailyMg: 30000,
    minAgeMonths: 1,
    minWeightKg: 4,
    sortOrder: 21,
    note: 'ყაბზობაზე. ეფექტი 1–2 დღეში ჩნდება; დოზა ინდივიდუალურად ირჩევა.',
    concentrations: [
      { label: 'სიროფი 667 მგ / 1 მლ', mg: 667, ml: 1 },
    ],
  },
  {
    slug: 'nystatin',
    name: 'ნისტატინი',
    dosingType: MedicationDosingType.BY_AGE,
    ageBands: [
      { label: 'ყველა ასაკი', untilMonths: 217, mg: 100000 },
    ],
    intervalHoursMin: 6,
    intervalHoursMax: 6,
    maxDailyMg: 800000,
    minAgeMonths: 0,
    minWeightKg: 2,
    sortOrder: 22,
    note: 'დოზა საერთაშორისო ერთეულებშია. პირის ღრუს კანდიდოზზე, კვების შემდეგ.',
    concentrations: [
      { label: 'სუსპენზია 100000 სე / 1 მლ', mg: 100000, ml: 1 },
    ],
  },
  {
    slug: 'mebendazole',
    name: 'მებენდაზოლი',
    dosingType: MedicationDosingType.BY_AGE,
    ageBands: [
      { label: '1 წლიდან', untilMonths: 217, mg: 100 },
    ],
    intervalHoursMin: 24,
    intervalHoursMax: 24,
    maxDailyMg: 200,
    minAgeMonths: 12,
    minWeightKg: 10,
    sortOrder: 23,
    note: 'პარაზიტების საწინააღმდეგო. მკურნალობა ოჯახის ყველა წევრს ერთდროულად.',
    concentrations: [
      { label: 'სუსპენზია 100 მგ / 5 მლ', mg: 100, ml: 5 },
    ],
  },
];
